#!/usr/bin/env python3
"""
Morning VC & Tech Newsletter Agent
Runs daily at 8am PT, uses Claude with web search to compile
personalized briefings on VC deals, AI, energy, and semiconductors.
"""

import os
import json
import smtplib
import anthropic
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime
import pytz

# ── Config (set these as environment variables or GitHub Actions secrets) ──────
ANTHROPIC_API_KEY = os.environ["ANTHROPIC_API_KEY"]
SENDER_EMAIL      = os.environ["SENDER_EMAIL"]       # Gmail address you send FROM
SENDER_PASSWORD   = os.environ["SENDER_PASSWORD"]    # Gmail App Password (not your login password)
RECIPIENT_EMAIL   = os.environ["RECIPIENT_EMAIL"]    # Where to deliver the newsletter


# ── Claude web-search prompt ───────────────────────────────────────────────────
SYSTEM_PROMPT = """You are a sharp, senior VC analyst writing a daily morning briefing
for a venture capital investor. Your reader is time-constrained and sophisticated —
they want signal, not noise.

Tone: direct, insightful, no filler. Write like a trusted colleague, not a journalist.
Format: clean HTML email (inline styles only, no external CSS).

Sections to cover (in order):
1. 💰 VC Deal Activity — notable funding rounds, exits, and firm news from the last 24 hours.
   Focus on: deal size, sector, lead investor, what it signals about the market.
2. 🤖 AI — most important developments for a VC: new models, infra plays, enterprise adoption,
   regulatory moves, and noteworthy research commercialization.
3. ⚡ Energy — cleantech deals, grid infrastructure, nuclear/fusion milestones, policy shifts
   that affect capital deployment.
4. 🔬 Semiconductors — fab news, chip design startups, supply chain shifts, government
   subsidies/CHIPS Act updates, and AI chip demand signals.

For each item include:
- A bolded 1-line headline
- 2–3 sentences of context: what happened, why it matters to a VC, what to watch
- Source name (no URLs needed)

End with a "So What?" section: 3 punchy bullet points on the single biggest cross-sector
theme of the day and what it means for dealflow or portfolio companies.

Search for today's news before writing. Be specific — include company names, dollar amounts,
and investor names wherever possible. Skip anything older than 48 hours."""

USER_PROMPT = f"""Today is {datetime.now(pytz.timezone('US/Pacific')).strftime('%A, %B %d, %Y')}.

Search for the latest news and compile today's morning briefing covering:
1. Significant VC deals and venture market activity
2. AI industry headlines (from a VC investor perspective)
3. Energy / cleantech headlines (from a VC investor perspective)
4. Semiconductor industry headlines (from a VC investor perspective)

Write the full briefing as a well-formatted HTML email I can send directly.
Use inline styles for formatting. Make it scannable with clear section headers."""


# ── HTML email wrapper ─────────────────────────────────────────────────────────
def wrap_in_email_template(content: str, date_str: str) -> str:
    return f"""<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"></head>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
             max-width: 680px; margin: 0 auto; padding: 24px;
             background: #ffffff; color: #1a1a1a; line-height: 1.6;">

  <div style="border-bottom: 3px solid #0f172a; padding-bottom: 16px; margin-bottom: 24px;">
    <h1 style="margin: 0; font-size: 22px; color: #0f172a; letter-spacing: -0.5px;">
      📬 Morning Briefing
    </h1>
    <p style="margin: 4px 0 0; font-size: 13px; color: #64748b;">{date_str}</p>
  </div>

  {content}

  <div style="border-top: 1px solid #e2e8f0; margin-top: 32px; padding-top: 16px;
              font-size: 12px; color: #94a3b8; text-align: center;">
    Generated by your Claude newsletter agent · {date_str}
  </div>

</body>
</html>"""


# ── Call Claude with web search ────────────────────────────────────────────────
def generate_newsletter() -> str:
    client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)

    print("🔍 Calling Claude with web search...")

    response = client.messages.create(
        model="claude-sonnet-4-20250514",
        max_tokens=4096,
        system=SYSTEM_PROMPT,
        tools=[{"type": "web_search_20250305", "name": "web_search"}],
        messages=[{"role": "user", "content": USER_PROMPT}],
    )

    # Extract the final text response (Claude may use tool calls mid-stream)
    newsletter_html = ""
    for block in response.content:
        if block.type == "text":
            newsletter_html += block.text

    if not newsletter_html.strip():
        raise ValueError("Claude returned no text content")

    print(f"✅ Newsletter generated ({len(newsletter_html)} chars)")
    return newsletter_html


# ── Send via Gmail SMTP ────────────────────────────────────────────────────────
def send_email(html_body: str, date_str: str):
    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"📬 Morning Briefing — {date_str}"
    msg["From"]    = SENDER_EMAIL
    msg["To"]      = RECIPIENT_EMAIL

    full_html = wrap_in_email_template(html_body, date_str)
    msg.attach(MIMEText(full_html, "html"))

    print(f"📧 Sending to {RECIPIENT_EMAIL}...")
    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(SENDER_EMAIL, SENDER_PASSWORD)
        server.sendmail(SENDER_EMAIL, RECIPIENT_EMAIL, msg.as_string())

    print("✅ Email sent!")


# ── Main ───────────────────────────────────────────────────────────────────────
def main():
    pt = pytz.timezone("US/Pacific")
    date_str = datetime.now(pt).strftime("%A, %B %d, %Y")

    print(f"\n🗞  Starting newsletter generation for {date_str}\n")

    newsletter_html = generate_newsletter()
    send_email(newsletter_html, date_str)

    print("\n🎉 Done!\n")


if __name__ == "__main__":
    main()
